import sgems
import csv

# 1. The output path of where to store the generated facies models
path = 'F:/8_project/7_Synthetic_4D_reservoir_Studies/synthetic_reservoir/4D_production_correlation/'
# read the input parameter file into a matrix 
list_of_lists = []
with open(path+'MC_Sample_set2.dat') as f:
    for line in f:
        inner_list = [elt.strip() for elt in line.split()]
		#print inner_list
        # in alternative, if you need to use the file content as numbers
        # inner_list = [int(elt.strip()) for elt in line.split(',')]
        list_of_lists.append(inner_list)
print list_of_lists[0][1]


#loop through each row of table
Nbreal=1  # Number of model generated by each combination of the parameter

nx = '200'
ny = '200'
nz = '1'

# import the parameters from the design table
sgems.execute('NewCartesianGrid  temp::'+nx+'::'+ny+'::'+nz+'::1.0::1.0::1.0::0::0::0')
for i in range(len(list_of_lists)):
	sgems.execute('RunGeostatAlgorithm  TetrisTiGen::/GeostatParamUtils/XML::<parameters>  <algorithm name="TetrisTiGen" />     <Grid value="temp" region=""  />  \
	   <Seed  value="'+str(list_of_lists[i][11])+'" />   \
	   <Nb_Realizations  value="'+str(Nbreal)+'" />   \
	   <Property  value="barrier_flow'+str(i)+'" />   \
	   <XmlFile>   <Tetris>   <Objects numObjects="1">    <ObjectManager numElements="1" numOperations="0" type="Element" name="fault">     <Element value="1" name="Cuboid">      <ShapeManager type="Cuboid" name="Cuboid" code="1">       <Dimension>        <dx>         <CDF name="Constant">          <mean>      \
	   <Params value="'+str(list_of_lists[i][8])+'" name="Constant"/>      \
	   </mean>         </CDF>        </dx>        <dy>         <CDF name="Constant">          <mean>           <Params value="1" name="Constant"/>          </mean>         </CDF>        </dy>        <dz>         <CDF name="Constant">          <mean>           <Params value="1" name="Constant"/>          </mean>         </CDF>        </dz>       </Dimension>       <Rotation>        <ax>         <CDF name="Constant">          <mean>           <Params value="0" name="Constant"/>          </mean>         </CDF>        </ax>        <ay>         <CDF name="Constant">          <mean>           <Params value="0" name="Constant"/>          </mean>         </CDF>        </ay>        <az>         <CDF name="Constant">          <mean>          \
	   <Params value="'+str(list_of_lists[i][9])+'" name="Constant"/>      \
	   </mean>         </CDF>        </az>       </Rotation>      </ShapeManager>     </Element>    </ObjectManager>   </Objects>   <Simulations numSimulations="1">    <Simulation name="Simulation 1">     <ObjectSimulated type="Single Object" name="fault"/>   \
	   <Stop target="'+str(list_of_lists[i][10])+'" type="proportion"/>    \
	   <positioning type="random"/>    </Simulation>   </Simulations>  </Tetris>  </XmlFile>   </parameters>   ')
	filename='R'+str(i)+'_barrier.out::gslib'
	sgems.execute('SaveGeostatGrid  temp::'+path+filename+'::0::barrier_flow'+str(i)+'__real0')
